### ISSUE TITLE
Can't run samples

### ISSUE THREAD

**Issue by nyck33** [CFMTech/Jupytab#54]
I followed the instructions like the kernel one before I do the run and get

```
(ml4t) nobu@LAPTOP-DNCQ5AAC:/mnt/d/nomura/Jupytab/jupytab-server/samples$ jupytab --config=config.ini
Starting Jupytab-Server 0.9.11
SSL not enabled
Start notebook AirFlights.ipynb on 127.0.0.1:51561
Start notebook RealEstateCrime.ipynb on 127.0.0.1:53339
Start notebook sklearn-classifier.ipynb on 127.0.0.1:48965
Your token is 02014868fe0eef123269397c5bc65a9608b3cedb73e3b84d8d02c220
        Please open : http://LAPTOP-DNCQ5AAC:8765/?security_token=02014868fe0eef123269397c5bc65a9608b3cedb73e3b84d8d02c220
INFO:/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/traitlets/traitlets.py:2551: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'kernel_gateway.notebook_http' instead of "'kernel_gateway.notebook_http'" if you require traitlets >=5.
INFO:  FutureWarning,
INFO:/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/traitlets/traitlets.py:2551: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '127.0.0.1' instead of "'127.0.0.1'" if you require traitlets >=5.
INFO:  FutureWarning,
INFO:[I 2023-06-11 20:00:30.941 KernelGatewayApp] Kernel started: a5183783-c079-46b8-b01d-805d50934493, name: jupytab-demo
INFO:/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/traitlets/traitlets.py:2551: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'kernel_gateway.notebook_http' instead of "'kernel_gateway.notebook_http'" if you require traitlets >=5.
INFO:  FutureWarning,
INFO:/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/traitlets/traitlets.py:2551: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '127.0.0.1' instead of "'127.0.0.1'" if you require traitlets >=5.
INFO:  FutureWarning,
INFO:[I 2023-06-11 20:00:30.945 KernelGatewayApp] Kernel started: 397d5904-d85b-4084-bbc5-ad0b5d14333a, name: jupytab-demo
INFO:/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/traitlets/traitlets.py:2551: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'kernel_gateway.notebook_http' instead of "'kernel_gateway.notebook_http'" if you require traitlets >=5.
INFO:  FutureWarning,
INFO:/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/traitlets/traitlets.py:2551: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '127.0.0.1' instead of "'127.0.0.1'" if you require traitlets >=5.
INFO:  FutureWarning,
INFO:[I 2023-06-11 20:00:30.991 KernelGatewayApp] Kernel started: 4c31b8dc-4d86-4d40-ad98-52fff3079d5a, name: jupytab-demo
INFO:[I 2023-06-11 20:00:32.224 KernelGatewayApp] Registering resource: /schema, methods: (['GET'])
INFO:[I 2023-06-11 20:00:32.224 KernelGatewayApp] Registering resource: /data, methods: (['GET'])
INFO:[I 2023-06-11 20:00:32.224 KernelGatewayApp] Registering resource: /_api/spec/swagger.json, methods: (GET)
INFO:[I 2023-06-11 20:00:32.225 KernelGatewayApp] Jupyter Kernel Gateway 2.5.2 is available at http://127.0.0.1:53339
INFO:[I 2023-06-11 20:00:32.317 KernelGatewayApp] Kernel shutdown: 397d5904-d85b-4084-bbc5-ad0b5d14333a
INFO:Traceback (most recent call last):
INFO:  File "/home/nobu/miniconda3/envs/ml4t/bin/jupyter-kernelgateway", line 8, in <module>
INFO:    sys.exit(launch_instance())
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/jupyter_core/application.py", line 269, in launch_instance
INFO:    return super().launch_instance(argv=argv, **kwargs)
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/traitlets/config/application.py", line 1042, in launch_instance
INFO:    app.initialize(argv)
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/kernel_gateway/gatewayapp.py", line 404, in initialize
INFO:    self.init_configurables()
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/kernel_gateway/gatewayapp.py", line 458, in init_configurables
INFO:    self.personality.init_configurables()
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/kernel_gateway/notebook_http/__init__.py", line 79, in init_configurables
INFO:    self.parent.kernel_manager
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/kernel_gateway/services/kernels/pool.py", line 69, in __init__
INFO:    super(ManagedKernelPool, self).__init__(prespawn_count, kernel_manager)
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/kernel_gateway/services/kernels/pool.py", line 31, in __init__
INFO:    self.kernel_manager.start_seeded_kernel()
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/kernel_gateway/services/kernels/manager.py", line 73, in start_seeded_kernel
INFO:    return ioloop.IOLoop.current().run_sync(start)
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/tornado/ioloop.py", line 529, in run_sync
INFO:    return future_cell[0].result()
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/tornado/gen.py", line 782, in run
INFO:    yielded = self.gen.send(value)
INFO:  File "/home/nobu/miniconda3/envs/ml4t/lib/python3.7/site-packages/kernel_gateway/services/kernels/manager.py", line 110, in start_kernel
INFO:    raise RuntimeError('Error seeding kernel memory', msg['content'])
INFO:RuntimeError: ('Error seeding kernel memory', {'status': 'error', 'traceback': ['\x1b[0;31m---------------------------------------------------------------------------\x1b[0m', '\x1b[0;31mModuleNotFoundError\x1b[0m                       Traceback (most recent call last)', '\x1b[0;32m/tmp/ipykernel_23794/582077492.py\x1b[0m in \x1b[0;36m<module>\x1b[0;34m\x1b[0m\n\x1b[1;32m      2\x1b[0m \x1b[0;32mimport\x1b[0m \x1b[0mnumpy\x1b[0m \x1b[0;32mas\x1b[0m \x1b[0mnp\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[1;32m      3\x1b[0m \x1b[0;32mimport\x1b[0m \x1b[0mjupytab\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0;32m----> 4\x1b[0;31m \x1b[0;32mfrom\x1b[0m \x1b[0msklearn\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mdatasets\x1b[0m \x1b[0;32mimport\x1b[0m \x1b[0mload_iris\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1;32m      5\x1b[0m \x1b[0;32mfrom\x1b[0m \x1b[0msklearn\x1b[0m\x1b[0;34m.\x1b[0m\x1b[0mneural_network\x1b[0m \x1b[0;32mimport\x1b[0m \x1b[0mMLPClassifier\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n', "\x1b[0;31mModuleNotFoundError\x1b[0m: No module named 'sklearn'"], 'ename': 'ModuleNotFoundError', 'evalue': "No module named 'sklearn'", 'engine_info': {'engine_uuid': '511500d1-c325-4ea9-b36b-7dc6ab25f0da', 'engine_id': -1, 'method': 'execute'}, 'execution_count': 1, 'user_expressions': {}, 'payload': []})
INFO:[I 2023-06-11 20:00:35.900 KernelGatewayApp] Registering resource: /schema, methods: (['GET'])
INFO:[I 2023-06-11 20:00:35.900 KernelGatewayApp] Registering resource: /data, methods: (['GET'])
INFO:[I 2023-06-11 20:00:35.900 KernelGatewayApp] Registering resource: /_api/spec/swagger.json, methods: (GET)
INFO:[I 2023-06-11 20:00:35.901 KernelGatewayApp] Jupyter Kernel Gateway 2.5.2 is available at http://127.0.0.1:51561

```

**Comment by btribonde** [comment]
According to the log you provided: \x1b[0;31mModuleNotFoundError\x1b[0m: No module named 'sklearn'

Required libraries have not been installed in your notebook kernel environment.

This tutorial may be helpful as it provides more details: https://towardsdatascience.com/interactive-simulation-with-tableau-and-jupytab-c26adb1be564
