### ISSUE TITLE
Block keyword, ZMQ, and Parent appears to have exited

### ISSUE THREAD

**Issue by Jabaker35** [CFMTech/Jupytab#55]
Starting Jupytab-Server 0.9.11
SSL not enabled
Start notebook C:\Users\Judie Baker\Desktop\repo-practice\Predictive-Analysis\jupytab.ipynb on 127.0.0.1:60977
You have no defined token. Please note your process is not secured !
        Please open : http://DESKTOP-ALF8KLJ:8765
INFO:C:\Users\Judie Baker\anaconda3\lib\site-packages\traitlets\traitlets.py:2544: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'kernel_gateway.notebook_http' instead of "'kernel_gateway.notebook_http'" if you require traitlets >=5.
INFO:  warn(
INFO:C:\Users\Judie Baker\anaconda3\lib\site-packages\traitlets\traitlets.py:2544: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '127.0.0.1' instead of "'127.0.0.1'" if you require traitlets >=5.
INFO:  warn(
INFO:[KernelGatewayApp] [nb_conda_kernels] enabled, 1 kernels found
INFO:[KernelGatewayApp] Kernel started: 86b8fb93-475b-4887-b114-b9f512b54b95, name: jupytab-sim-demo
INFO:Traceback (most recent call last):
INFO:  File "C:\Users\Judie Baker\anaconda3\Scripts\jupyter-kernelgateway-script.py", line 9, in <module>
INFO:    sys.exit(launch_instance())
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\jupyter_core\application.py", line 277, in launch_instanceINFO:    return super().launch_instance(argv=argv, **kwargs)
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\traitlets\config\application.py", line 991, in launch_instance
INFO:    app.initialize(argv)
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\kernel_gateway\gatewayapp.py", line 395, in initialize
INFO:    self.init_configurables()
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\kernel_gateway\gatewayapp.py", line 449, in init_configurables
INFO:    self.personality.init_configurables()
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\kernel_gateway\notebook_http\__init__.py", line 77, in init_configurables
INFO:    self.kernel_pool = ManagedKernelPool(
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\kernel_gateway\services\kernels\pool.py", line 69, in __init__
INFO:    super(ManagedKernelPool, self).__init__(prespawn_count, kernel_manager)
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\kernel_gateway\services\kernels\pool.py", line 31, in __init__
INFO:    self.kernel_manager.start_seeded_kernel()
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\kernel_gateway\services\kernels\manager.py", line 73, in start_seeded_kernel
INFO:    return ioloop.IOLoop.current().run_sync(start)
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\tornado\ioloop.py", line 529, in run_sync
INFO:    return future_cell[0].result()
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\tornado\gen.py", line 782, in run
INFO:    yielded = self.gen.send(value)
INFO:  File "C:\Users\Judie Baker\anaconda3\lib\site-packages\kernel_gateway\services\kernels\manager.py", line 104, in start_kernel
INFO:    msg = client.shell_channel.get_msg(block=True)
INFO:TypeError: get_msg() got an unexpected keyword argument 'block'
INFO:[KernelGatewayApp] WARNING | Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x000001D127310400>
INFO:[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

The crazy thing is I have uninstalled ZMQ and reinstalled it. Still didn't work.

**Comment by btribonde** [comment]
Hello,

Windows version should work but is not tested, please provide a merge request if you can found a solution to your issue.

**Comment by Jabaker35** [comment]
I am using Windows when I use your program.
